---

##########################################################
# AWS Configuration file for NodeJS Deploy GitHub Action #
#                                                        #
# NOTE: This file holds the variables needed             #
# to configure the GitHub Deploy NodeJS                  #
# on AWS Serverless                                      #
#                                                        #
# This file needs to be in the location:                 #
# - .github/aws-config.yml                               #
# in your repository to be parsed at run time            #
##########################################################

########################################
# AWS S3 Bucket for package and deploy #
########################################
# NOTE: This bucket must exist before the GitHub Action
s3_bucket:

##################################
# AWS Cloud Formation Stack name #
##################################
# NOTE: Defaults to "mystack" if left empty
aws_stack_name: mystack

######################
# AWS Capability IAM #
######################
# NOTE: This needs the capabilities to build and deploy your SAM
aws_capability_iam:

###########################################
# aws_access_key_id for connection to AWS #
###########################################
# NOTE: this AWS key needs all access to build and deploy SAM
aws_access_key_id:

###############################################
# aws_secret_access_key for connection to AWS #
###############################################
# NOTE: this AWS key needs all access to build and deploy SAM
aws_secret_access_key:

################################
# region for connection to AWS #
################################
# Default region is: us-west-2
# if not provided below
region: us-west-2

################################
# output for connection to AWS #
################################
# Default output is: json
# if not provided below
output: json
